import LegalLayout, { LegalSection } from './LegalLayout'

type PrivacyPolicyProps = {
  onBack: () => void
}

function PrivacyPolicy({ onBack }: PrivacyPolicyProps) {
  return (
    <LegalLayout title="Privacy Policy" onBack={onBack}>
      <LegalSection title="1. Controller">
        <p>
          Bidly Inc.
          <br />
          Leubnitzer Str. 28, 01069 Dresden, Germany
          <br />
          Email: contact@bidly.example{' '}
          <span className="italic">(placeholder — replace with a real, monitored contact address)</span>
        </p>
      </LegalSection>

      <LegalSection title="2. What data we process">
        <p>When you use the Information Gathering voice conversation, we process:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>
            Your microphone audio, streamed live to our voice AI provider, ElevenLabs, over an encrypted WebRTC
            connection, in order to hold the conversation.
          </li>
          <li>
            The resulting conversation transcript and the structured event details you share (e.g. date, budget,
            guest count, preferences), which ElevenLabs analyzes and which our server retrieves via the ElevenLabs
            API once the call ends.
          </li>
          <li>
            Standard technical/access data generated by your browser and our hosting provider while you use the
            site (e.g. IP address, timestamps), used for security and operational purposes.
          </li>
        </ul>
        <p>
          If you use the "Download JSON" button, the resulting file is generated locally in your browser and saved
          to your own device — it is not transmitted to us.
        </p>
      </LegalSection>

      <LegalSection title="3. Legal basis">
        <p>
          We process this data based on Art. 6(1)(b) GDPR (performance of a contract, i.e. to provide the service
          you requested) and, for microphone access specifically, your explicit consent under Art. 6(1)(a) GDPR,
          given each time your browser prompts you to allow microphone access.
        </p>
      </LegalSection>

      <LegalSection title="4. Recipients / third-party processors">
        <p>
          We use ElevenLabs Inc. as a voice AI processor to conduct the conversation and analyze its content. See{' '}
          <a
            href="https://elevenlabs.io/legal/privacy-policy"
            target="_blank"
            rel="noreferrer"
            className="text-primary underline"
          >
            ElevenLabs' privacy policy
          </a>{' '}
          for details of their own processing. Depending on configuration, this may involve data transfers outside
          the European Economic Area; where this occurs, ElevenLabs is responsible for ensuring appropriate
          safeguards (e.g. Standard Contractual Clauses).
        </p>
      </LegalSection>

      <LegalSection title="5. Storage duration">
        <p>
          Conversation transcripts and extracted event details are retained by ElevenLabs according to their own
          data-retention policy. We do not separately store this data on our own servers beyond what is needed to
          display it to you in your current browser session.
        </p>
      </LegalSection>

      <LegalSection title="6. Cookies and local storage">
        <p>
          This application does not set tracking or advertising cookies and does not use analytics. Any state (such
          as your progress through the voice-intake flow) is kept only in your browser's memory for the duration of
          your visit and is lost when you close or refresh the page.
        </p>
      </LegalSection>

      <LegalSection title="7. Your rights">
        <p>Under the GDPR, you have the right to:</p>
        <ul className="list-disc space-y-1 pl-5">
          <li>access the personal data we hold about you (Art. 15),</li>
          <li>request rectification of inaccurate data (Art. 16),</li>
          <li>request erasure of your data (Art. 17),</li>
          <li>request restriction of processing (Art. 18),</li>
          <li>receive your data in a portable format (Art. 20),</li>
          <li>object to processing (Art. 21), and</li>
          <li>
            lodge a complaint with a supervisory authority, such as the Saxon Data Protection Commissioner
            (Sächsischer Datenschutzbeauftragter) or your own local authority.
          </li>
        </ul>
      </LegalSection>

      <LegalSection title="8. Contact">
        <p>
          For any privacy-related questions or requests, contact us at contact@bidly.example{' '}
          <span className="italic">(placeholder — replace with a real, monitored contact address)</span>.
        </p>
      </LegalSection>

      <LegalSection title="9. Changes to this policy">
        <p>
          We may update this privacy policy from time to time to reflect changes to our practices or for legal
          reasons. The current version is always available on this page.
        </p>
      </LegalSection>
    </LegalLayout>
  )
}

export default PrivacyPolicy
